rust-av/rust-av

README.md
Adding basic instructions to compile and run tests
=> adding build and test instructions

.travis.yml
Coveralls may take a bit of working with to get all the coverage for, ideally this will work perfectly as it is.
Fixes #43
=> Test splitting tests of crates to ensure all gets tested

bitstream/src/bitread.rs, bitstream/src/bytewrite.rs, bitstream/src/codebook.rs, bitstream/src/lib.rs, codec/src/decoder.rs, codec/src/encoder.rs, codec/src/lib.rs, data/src/audiosample.rs, data/src/frame.rs, data/src/lib.rs, data/src/packet.rs, data/src/params.rs, data/src/pixel.rs, data/src/timeinfo.rs, data/src/value.rs, format/src/buffer/accreader.rs, format/src/common.rs, format/src/demuxer.rs, format/src/lib.rs, format/src/muxer.rs, format/src/stream.rs, src/io/byteread.rs, src/lib.rs
=> 2018 edition

.travis.yml, bitstream/src/bitread.rs, codec/src/decoder.rs, codec/src/encoder.rs, data/src/audiosample.rs, data/src/frame.rs, data/src/packet.rs, data/src/pixel.rs, format/src/buffer/accreader.rs, format/src/demuxer.rs, format/src/muxer.rs, format/src/stream.rs, src/io/byteread.rs
Signed-off-by: gibix <gibix@riseup.net>
=> lint and stable

data/src/pixel.rs
Signed-off-by: gibix <gibix@riseup.net>
=> add chromaton constructor

.github/workflows/rust-av.yml
- Remove wrong coverage job
- Add `clippy-check`
=> Modify Github Actions

codec/Cargo.toml
Signed-off-by: gibix <gibix@riseup.net>
=> codec: update data

data/src/audiosample.rs, data/src/pixel.rs
From the hacktoberfest issues I've just started writing some documentation for the code as I understand it from reading. Currently done most of `audio_sample` I'll look over the rest of the codebase and fill in what I can.
Creating this PR for early critique in case any of my understanding is off :+1: also I don't know what the different `ChannelTypes` are from their initials
=> Add some documentation (WIP)

.github/workflows/rust-av.yml
- Update `action-rs` actions
- Add `macOS`
The `clippy-rustfmt` failure is right, there is a problem with code formatting.
=> Update Github Actions

bitstream/src/bytewrite.rs, data/src/audiosample.rs, data/src/pixel.rs, format/src/demuxer.rs
My rust fmt like I did in #97 to let it get merged first
=> Ran rustfmt

bitstream/Cargo.toml, bitstream/src/codebook.rs, codec/Cargo.toml, codec/src/error.rs, data/Cargo.toml, data/src/frame.rs, format/Cargo.toml, format/src/error.rs
=> Replace err-derive with thiserror

Cargo.toml, README.md, examples/streams_info.rs
=> Add a simple example

.github/workflows/rust-av.yml, Cargo.toml, README.md, examples/Cargo.toml, examples/README.md, examples/examples/frames_info.rs, examples/examples/streams_info.rs
=> Add a crate for examples

bitstream/src/bitread.rs, bitstream/src/byteread.rs, bitstream/src/bytewrite.rs, bitstream/src/codebook.rs
=> Document the bitstream crate

codec/src/common.rs, codec/src/decoder.rs, codec/src/encoder.rs, codec/src/error.rs
This fixes the second item of #119 
=> Document the codec crate

data/src/audiosample.rs, data/src/packet.rs, data/src/params.rs, data/src/pixel.rs, data/src/timeinfo.rs, data/src/value.rs
This fixes the third item of #119
=> Document the data crate

format/src/buffer/accreader.rs, format/src/buffer/mod.rs, format/src/common.rs, format/src/demuxer.rs, format/src/error.rs, format/src/muxer.rs, format/src/stream.rs
=> Document the format crate

data/src/frame.rs, data/src/pixel.rs
This PR documents, refactors and expands frame info structures.
=> Expand frame info structures

data/src/frame.rs
=> Fix vulnerability in a frame function

data/src/frame.rs
This PR pre-allocates planes beforehand
=> data: Pre-allocate planes

data/src/frame.rs
- Move private functions into the `Frame` struct
- Document the `Frame` struct
- Remove same functions
=> data: Refactor the Frame struct

format/src/buffer/accreader.rs
There were some bugs when seeking when there was bytes remaining in the buffer, as well as reading when the internal buffer is too small for the read.
=> format: Fix AccReader reading and seeking

format/src/muxer.rs
Adds a Writer enum which wraps both Seekable (Write + Seek) and non-seekable (Write) trait objects.
Not sure if this is a good design, but it worked for my purposes. Open for discussion!
=> format: Add Writer for Seek and non-Seek output

format/src/demuxer.rs
Allows seeking directly from demuxers.
=> format: Pass &mut Buffered to demuxers

bitstream/src/codebook.rs
Reading codes using Codebook incorrectly checked for remaining bits using `self.left()` (internal 8-byte buffer) rather than `self.available()`.
=> bitstream: Fix reading codes on padding boundary

bitstream/src/codebook.rs
Also relaxes the mutable requirement on the codebook descriptions when creating a codebook.
=> bitstream: Implement CodebookDescReader for slices

bitstream/src/bytewrite.rs
=> Remove unnecessary mutable borrow

bitstream/src/bitread.rs, codec/src/error.rs, data/src/audiosample.rs, data/src/frame.rs, data/src/pixel.rs, format/src/error.rs
=> fix spelling error

format/src/muxer.rs
=> Improve muxer tests

format/src/muxer.rs
`Seek` can be implemented specifically for writers where `W: Seek`,
and this avoids the caller from having to specify a useless generic
type in addition to the real type being used.
Ideally I would've realized this before releasing the new version,
but I only discovered how un-ergonomic the current pattern is
when attempting to implement it in rav1e.
=> Simplify `Muxer` trait to have one generic
