rust-av/rust-av

- .travis.yml
travis-cargo isn't maintained, and as of late, is broken outright https://travis-ci.org/rust-av/rust-av/builds/332787331#L1270 and https://github.com/huonw/travis-cargo/issues/72. This pull request instead takes advantage of https://github.com/roblabla/cargo-travis which is actively maintained with the goals to replace travis-cargo along with eventually reaching feature parody.
EDIT: Forgot travis makes multiple builds when you split env keys, will amend commit with the correct setting.
> ci: Move to cargo-travis

- Cargo.toml
- codec/Cargo.toml
- data/Cargo.toml
- format/Cargo.toml
Recently the project got relicensed under the MIT license.
Add license = "MIT" to the Cargo.toml to make the license clear.
> Add the MIT license to all crates

- bitstream/src/lib.rs
- codec/src/lib.rs
- data/src/frame.rs
- data/src/lib.rs
- format/src/lib.rs
- src/lib.rs
- lint "unused_doc_comment" has been renamed to "unused_doc_comments"
- alloc::heap has been partially moved to alloc::alloc
> Fix nightly regressions

- README.md
- appveyor.yml
Was relatively easy, so here's AppVeyor config. AppVeyor needs to be [enabled](https://github.com/marketplace/appveyor) in the GitHub Marketplace.
`x86_64-pc-windows-msvc` on Rust `stable` fails because `rust_2018_preview` is used.
```
Compiling av-codec v0.1.0 (C:\projects\rust-av\codec)
error[E0554]: #![feature] may not be used on the stable release channel
--> codec\src\lib.rs:5:1
|
5 | #![feature(box_syntax, plugin, rust_2018_preview)]
| ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
error: aborting due to previous error
```
`aarch64-pc-windows-msvc` fails because [winapi-rs](https://github.com/retep998/winapi-rs) can't deal with aarch64 targets (see https://github.com/retep998/winapi-rs/issues/727 and https://github.com/retep998/winapi-rs/issues/728).
For now they are both …
> Add continuous integration on Windows with AppVeyor

- Cargo.toml
- bitstream/Cargo.toml
- bitstream/src/bitread.rs
- bitstream/src/byteread.rs
- bitstream/src/bytewrite.rs
- bitstream/src/codebook.rs
- bitstream/src/lib.rs
- codec/Cargo.toml
- codec/src/common.rs
- codec/src/decoder.rs
- codec/src/encoder.rs
- data/Cargo.toml
- data/src/frame.rs
- data/src/packet.rs
- data/src/params.rs
- data/src/pixel.rs
- data/src/timeinfo.rs
- data/src/value.rs
- format/Cargo.toml
- format/src/buffer/accreader.rs
- format/src/common.rs
- format/src/demuxer.rs
- format/src/lib.rs
- format/src/muxer.rs
- format/src/stream.rs
- src/io/byteread.rs
- src/lib.rs
This PR contains a host of fixes and formatting changes that update `rust-av` for compilation on Rust's 2018 Edition. I can roll up these changes if that's preferable, but I wanted to leave them separate by default to make cherry-picking easier.
Hopefully, these changes will also mean `rust-av` can drop the requirement on `rustc +nightly`, too, but that vision has yet to be fully realized.
Looking at issues, it seems that merging this PR would resolve #61 (again, because best practices have shifted, I believe).
> Update to Rust 2018 Edition

- format/src/demuxer.rs
ok, so here is a quick fix for the issue of `matroska_remux` not writing the `Cluster` element.
What's happening:
- in the MKV demuxer, we want to ignore elements between `Tracks` and `Cluster` (most likely, we're ignoring a `Tags` element: https://github.com/rust-av/matroska/blob/master/src/demuxer.rs#L151-L155
- since it returned `MoreDataNeeded(0)`, we're in the general demuxer code's case where we want to seek and request more data: https://github.com/rust-av/rust-av/blob/master/format/src/demuxer.rs#L106-L108
- we ask for more data, so we try to grow the buffer, but for a small file, we probably already read everything, so it returns EOF: https://github.com/rust-av/rust-av/blob/master/format/src/demuxer.rs#L131-L136
- that EOF events bubbles up to matroska_remux, so we do not …
> handle the case where we want to demux again but don't need more data

- format/Cargo.toml
- format/src/demuxer.rs
I would bump it as 0.2.0 and then bake a release.
> Make the Event non-exaustive

- bitstream/src/byteread.rs
- bitstream/src/bytewrite.rs
- bitstream/src/lib.rs
Remove unsafe operations from the `bitstream` crate, replacing them with safe functions. If I'm not mistaken, this PR closes #38 and #39
> Replace unsafe operations

- format/src/demuxer.rs
Now that `Rust 1.40` is out, we can use it
> Use the new non_exhaustive attribute

- bitstream/Cargo.toml
- bitstream/src/bytewrite.rs
The usage of `to_vec` clones the input slice,
meaning the original input buffer is never written to.
> Fix bytewrite methods for types other than u8

- Cargo.toml
- examples/Cargo.toml
- format/Cargo.toml
- format/src/muxer.rs
This allows writing to other sources, e.g. Files, directly,
without an intermediate Vec buffer.
Closes #123.
> Change Muxer trait to take `&mut Write`

- data/src/timeinfo.rs
This PR clarifies for what  the `TimeInfo` struct is used and makes the explanation of the `timebase` field more precise.
> Clarify timeinfo documentation

- codec/src/decoder.rs
- format/src/buffer/accreader.rs
- format/src/buffer/mod.rs
- format/src/demuxer.rs
This PR adds the `Sync` trait to some of the traits implemented in `rust-av` in order to use them concurrently.
> Add Sync trait to some `rust-av` traits to use them concurrently 

- format/src/demuxer.rs
This PR:
- Replace Box with a generic for Reader
- Replace Box with a generic for Demuxer
- Add an API to retrieve the underlying demuxer
> Add generics in demuxer code

- format/src/muxer.rs
This PR:
- Replace Box with a generic for Muxer
- Replace Box with a generic for Writer
- Add an API to retrieve the underlying muxer
- Add some APIs to retrieve the underlying buffer
- Add tests for muxer
> Add generics in muxer code 

- codec/src/encoder.rs
This PR:
- Replace Box with a generic for Encoder
- Add an API to retrieve the underlying encoder
> Add generic in encoder code

- format/src/muxer.rs
This PR adds an `API` to muxer to check whether a source is seekable
> Add an API to check if a source is seekable

- codec/src/decoder.rs
- codec/src/encoder.rs
This PR:
- Replace Box with a generic for Decoder
- Add an API to retrieve the underlying decoder
- Clean up encoder and decoder code a bit
> Add generics in decoder code

- format/src/muxer.rs
This PR:
- Allows to retrieve a buffer from within the `Muxer` trait
- Adds an API to retrieve the stream position
> Make the muxer writer more generic

- data/Cargo.toml
- data/src/frame.rs
This PR fixes an API misuse, `BytesMut` was reading not yet initialized memory. This also fixes a test on Windows.
> Fix an API misuse

- data/src/frame.rs
This PR adds a `SAFETY` comment to the unique unsafe block in the code
> Add a safety comment to unsafe code

- bitstream/src/bitread.rs
- bitstream/src/byteread.rs
- bitstream/src/bytewrite.rs
- bitstream/src/codebook.rs
- bitstream/src/lib.rs
- codec/src/decoder.rs
- codec/src/encoder.rs
- codec/src/lib.rs
- data/src/audiosample.rs
- data/src/frame.rs
- data/src/lib.rs
- data/src/packet.rs
- data/src/params.rs
- data/src/pixel.rs
- data/src/timeinfo.rs
- data/src/value.rs
- format/src/demuxer.rs
- format/src/lib.rs
- format/src/muxer.rs
- src/lib.rs
This enforces via the compiler that all public items are documented, and adds documentation for items that did not have it.
> Document all public items

- data/CHANGELOG.md
- data/Cargo.toml
- data/src/frame.rs
Using `with_capacity` does not initialize any data, so when the `split_to` API is called, a panic is raised
> Use initialized data for a new frame 

- data/src/pixel.rs
This PR adds RGB48 (RGB, 16-bits per channel) and RGBA64 (RGBA, 16-bits per channel) formatons. 
See: #47
> pixel: Add higher bitdepth RGB formatons

- Cargo.toml
- benches/bench.rs
- benches/bitstream.rs
- benches/format.rs
This PR adds benchmarks for the followings by utilizing [criterion](https://github.com/japaric/criterion.rs):
1. Bit reading operations with `BitReadLE`: `get_bits_32`, `peek_bits_32`, and `skip_bits`
2. Byte reading operations with `AccReader`: `read_exact` 
See: #36
> Add benchmarks with criterion

- bitstream/src/bytewrite.rs
- data/src/audiosample.rs
- data/src/frame.rs
- data/src/pixel.rs
- format/src/demuxer.rs
- src/io/byteread.rs
Not much to say, this is a fundamental trait that can be helpful if you want to use a type in a `HashMap` or something similar. I didn't derive it for every trait in av-data because some have heap-allocated types and manual `PartialEq`/`Eq` implementations (`Hash` and `Eq` have a [special relation](https://doc.rust-lang.org/std/hash/trait.Hash.html#hash-and-eq) to one another).
> data: Derive Hash impl for some types

- data/Cargo.toml
- data/src/frame.rs
The `thiserror` change is trivial. I'm split on the `num_derive` replacement.
I've manually implemented `FromPrimitive`/`ToPrimitive` for enums with few variants that are unlikely to change. For those, it seems fine to just write the boiler plate. But for these larger enums, I wanted more robustness so I wrote a declarative macro. I'm confident that it works, but I'm not sure if this is code is nice enough to replace a `#[derive]`.
But, with this change:
```sh
$ cargo tree -p av-data -e normal | grep -c syn
0
```
Let me know what you think.
> data: Remove `thiserror` dependency

- bitstream/Cargo.toml
- bitstream/src/codebook.rs
- codec/Cargo.toml
- codec/src/error.rs
- format/Cargo.toml
- format/src/error.rs
Related to #193. I don't think adding `thiserror` for these simple error types is necessary, and `thiserror` recently updated to v2.0 (see #196). I have a feeling this will cause some fragmentation over time (some older crates depend on 1, while newer crates update to 2) and entirely removing `thiserror` alleviates that problem for dependent crates.
> Remove thiserror dependency from all crates in this repository
